### ISSUE TITLE
Fallo en RegistroGrupoCrossRef

### ISSUE THREAD

**Issue by Pp-wveDev** [alejandroat99/ControlGastos#1]
No me deja probar las vistas :( Intenta que todo funcione antes de hacer push porfi

![image](https://user-images.githubusercontent.com/73610677/101985640-af0d4280-3c89-11eb-9e98-4066108d3def.png)

**Comment by Pp-wveDev** [comment]
No te toco nada por si acaso

**Comment by Pp-wveDev** [comment]
Esto creo que lo tienes que cambiar, que se te habrá pasado, y aparte luego hay otras cosas que fallan

![image](https://user-images.githubusercontent.com/73610677/101985706-f7c4fb80-3c89-11eb-9616-e08ccf00ed87.png)

**Comment by alejandroat99** [comment]
Ya están erreglados los errores que no permitían hacer build del proyecto. 
La solución se encuentra en la versión [e99ac0f869224a9e5499f68b80e4197cc9e52986](https://github.com/alejandroat99/ControlGastos/commit/74e99b3ada0e6c314d06b218276eda5324c93252)
